# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HqmjT__upLG8XDOqal-mVBO8k0FfoJ6
"""

# Install the Google AI Python SDK
!pip install -q -U google-generativeai

# Import necessary libraries
import google.generativeai as genai
from google.colab import userdata
from IPython.display import Markdown
import numpy as np
import scipy.io.wavfile
import cv2

# Configure the API key
try:
    # Get the API key from Colab secrets
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=GOOGLE_API_KEY)
    print("API Key configured s+uccessfully!")
except userdata.SecretNotFoundError as e:
    print(f"Secret not found: {e}")
    print("Please follow Step 2A to store your API key in Colab secrets.")

"""#Guided Reflective Diagnostic Reasoning (RDR) Framework

This prompt is designed to instruct a large, multimodal foundation model (like Gemini 2.5 Pro) to perform an expert-level diagnostic analysis of aviation maintenance data. Its primary goal is to produce a reliable, structured, and auditable report from unstructured inputs (video, audio, sensor data).

Methodology: Guided Reflective Diagnostic Reasoning (RDR)
The prompt implements a four-phase cognitive framework that forces the model to mimic the rigorous workflow of a human expert.

Phase 1: Guided Independent Analysis
The model is instructed to analyze each data stream (visual, audio, sensor) independently by answering specific guiding questions. This prevents it from jumping to premature conclusions.

Phase 2: Cross-Modal Synthesis & Self-Critique
The model must then correlate its findings across the different modalities. Critically, it is required to state its own confidence level and identify any ambiguities or missing information, making its reasoning process transparent.

Phase 3: Formalized Diagnostic Report & Classification
Based on the vetted analysis from Phase 2, the model generates a structured JSON report. This report includes a formal diagnosis, evidence, and a crucial triage_classification ('Good', 'Bad', or 'Not Bad') for rapid decision-making.

Phase 4: Executive Summary
The final step is to produce a concise, human-readable paragraph that summarizes the most critical findings and recommended actions.

Usage
This prompt is intended for zero-shot or few-shot inference. The user provides the prompt text, a single video file (with embedded audio), and the corresponding sensor data as a string. The model's output will be the complete four-phase analysis.
"""



#Zero shot
import google.generativeai as genai
from google.colab import userdata
from IPython.display import Markdown
import time

# --- Setup and Configuration ---
# Ensure your API key is stored in Colab Secrets as 'GOOGLE_API_KEY'
try:
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=GOOGLE_API_KEY)
    print("API Key configured successfully.")
except Exception as e:
    print(f"API Key not found or invalid. Please check your Colab Secrets. Error: {e}")

# --- Your entire workflow starts here ---

# 1. Define your source video filename
video_filename = "test_trubine_sd.mp4"

# 2. Select the model for the highest reasoning capability
model = genai.GenerativeModel(model_name="gemini-2.5-flash") # or pro

# 3. Upload your video file
print(f"Uploading your video file: {video_filename}...")
your_video_file = genai.upload_file(path=video_filename)
print(f"Upload complete. File Name: {your_video_file.name}")

# 4. Wait for the file to be processed and become ACTIVE
print(f"Processing file: {your_video_file.name}...")
while your_video_file.state.name == "PROCESSING":
    print("File is still processing, waiting 10 seconds...")
    time.sleep(10)
    your_video_file = genai.get_file(name=your_video_file.name)

if your_video_file.state.name == "FAILED":
    raise ValueError(f"File processing failed: {your_video_file.state.name}")
print(f"File is now ACTIVE and ready to use.")

# 5. Define your sensor data and the new, enhanced RDR prompt
sensor_data_csv = """ timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0,845,91.5,0.8
1,846,91.5,0.8
2,845,91.6,0.9
3,844,91.5,0.8
4,845,91.5,0.8
5,846,91.6,0.9
6,845,91.5,0.8
7,844,91.5,0.8
8,845,91.6,0.9
9,846,91.5,0.8
10,845,91.5,0.8
11,845,91.5,2.1
12,846,91.6,0.9
13,845,91.5,0.8
14,844,91.5,0.8
15,845,91.6,0.9
16,846,91.5,0.8
17,845,91.5,0.8
18,844,91.6,0.9
19,845,91.5,0.8
20,846,91.5,0.8
21,845,91.6,0.9
22,844,91.5,0.8
23,845,91.5,0.8
24,846,91.5,0.9
""" # Using only a short snippet for this example

# +++ ENHANCED PROMPT WITH GUIDING QUESTIONS, EXAMPLES, AND A FINAL SUMMARY STEP +++
prompt = """
**SYSTEM INSTRUCTION: GUIDED REFLECTIVE DIAGNOSTIC REASONING (RDR) FRAMEWORK**

You are AeroQwen, an expert-level Aviation Maintenance Diagnostics System. Your task is to perform a Guided RDR analysis on the provided data for '{video_filename}'. You MUST follow this four-phase process meticulously.

**Phase 1: Guided Independent Analysis**
Answer the following questions to analyze each data stream in isolation.
1.  **Visual Context & Anomalies:** What is the context of the video (e.g., operational flight, ground inspection)? Are there any visible anomalies like cracks, fractures, discoloration, or missing material? Note their timestamps.
2.  **Audio Context & Anomalies:** Is the audio consistent with the visual context? Are there any unexpected sounds like impacts, grinding, or abnormal whirring?
3.  **Sensor Data Context & Anomalies:** Does the sensor data show a normal operational state, or are there spikes, drops, or erratic behavior? Does the data's timeframe appear to match the visual context?

**Phase 2: Cross-Modal Synthesis & Self-Critique**
Synthesize your findings and critically evaluate your analysis.
1.  **Correlation:** Explicitly state the correlations (or lack thereof) between your answers above.
2.  **Confidence Assessment:** State your confidence level (High, Medium, Low).
3.  **Self-Critique:** Identify any ambiguities or missing information.

**Phase 3: Formalized Diagnostic Report & Classification**
Based ONLY on your synthesized analysis from Phase 2, generate the final, structured JSON report.
- The report must be complete, accurate, actionable, and include the source video filename.
- **Crucially, the report MUST also include a `triage_classification` field.** This field's value must be one of the following three strings, based on your analysis:
    - **'Good'**: Use if no significant faults are detected and the component is fully serviceable.
    - **'Bad'**: Use if critical, unserviceable damage is detected.
    - **'Not Bad'**: Use if minor wear or cosmetic issues are detected, but the component is still considered serviceable and requires only monitoring.

**Phase 4: Executive Summary**
After generating the JSON report, provide a concise, human-readable summary. This summary must begin with the final classification, followed by the main finding, severity, and primary recommended action. For example: "Classification: Bad. The system has detected critical damage..."

--- SENSOR DATA ---
{sensor_data}
--- END SENSOR DATA ---

Now, begin your Guided RDR analysis on the attached video file.
""".format(video_filename=video_filename, sensor_data=sensor_data_csv)


# 6. Send the request to the Gemini API
print("\nSending request to the Gemini API...")
response = model.generate_content([prompt, your_video_file])

# 7. Display the result
print("\n--- Model Response ---")
Markdown(response.text)
/teat_turbine_N_2.mp4

#Single shot
import google.generativeai as genai
from google.colab import userdata
from IPython.display import Markdown
import time

# --- Setup and Configuration ---
# Ensure your API key is stored in Colab Secrets as 'GOOGLE_API_KEY'
try:
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=GOOGLE_API_KEY)
    print("API Key configured successfully.")
except Exception as e:
    print(f"API Key not found or invalid. Please check your Colab Secrets. Error: {e}")

# --- 1. Define Your Single-Shot Example (Your Best "Bad Condition" Ground Truth) ---
# For a single-shot prompt, we provide just one, high-quality example.
# This one teaches the model what a critical fault report should look like.

single_shot_example = [
    {
        "description": "Bad Condition (FOD) Example",
        "video_filename": "Turbine_bad_FOD_1.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
4.4,650.1,85.2,1.8
4.5,980.5,82.1,55.9
4.6,950.2,75.4,58.2
""",
        "ground_truth_json": """{
  "fileName": "Turbine_bad_FOD_1.mp4",
  "diagnosticSummary": "Severe Foreign Object Damage (FOD) detected on multiple fan blades.",
  "confidence": "High",
  "severity": "Critical",
  "triage_classification": "Bad",
  "recommendedActions": [ "Ground the aircraft immediately. Do not attempt to start the engine." ],
  "evidence": { "visual": "Borescope footage shows multiple fan blades with large fractured sections and missing material." }
}"""
    }
]

# --- 2. Define your NEW test video and sensor data ---
# This is the video the model has not seen before.
test_video_filename = "Turbine_bad_1.mp4" # This should be one of your 12 test videos
test_sensor_data_csv = """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0.0,25.0,0.0,0.1
1.0,25.0,0.0,0.1
2.0,25.0,0.0,0.1
"""

# --- 3. Set up the model and upload the NEW test video ---
model = genai.GenerativeModel(model_name="gemini-2.5-pro")

print(f"Uploading your TEST video file: {test_video_filename}...")
test_video_file = genai.upload_file(path=test_video_filename)
print(f"Upload complete. File Name: {test_video_file.name}")

# Wait for the file to become ACTIVE
print(f"Processing file: {test_video_file.name}...")
while test_video_file.state.name == "PROCESSING":
    print("File is still processing, waiting 10 seconds...")
    time.sleep(10)
    test_video_file = genai.get_file(name=test_video_file.name)
if test_video_file.state.name == "FAILED":
    raise ValueError("File processing failed.")
print("File is now ACTIVE and ready to use.")

# --- 4. Construct the Final Single-Shot Prompt ---
# Format the single example into a string.
example_string = ""
for ex in single_shot_example:
    example_string += f"""
--- EXAMPLE START: {ex['description']} ---
USER INPUT:
Source Video File: {ex['video_filename']}
Sensor Data:
{ex['sensor_data']}
(The user would attach the video file '{ex['video_filename']}' here.)

ASSISTANT OUTPUT (The expected perfect response):
Phase 1, 2, 3, and 4 analysis would lead to this final JSON:
{ex['ground_truth_json']}
--- EXAMPLE END ---
"""

# Now, create the main prompt that includes the instructions, the single example, and the new case.
final_prompt = f"""
**SYSTEM INSTRUCTION: GUIDED REFLECTIVE DIAGNOSTIC REASONING (RDR) FRAMEWORK**
You are AeroQwen, an expert-level Aviation Maintenance Diagnostics System. Your task is to perform a Guided RDR analysis. First, study the example below to understand the expected reasoning process and output format. Then, apply the same rigorous analysis to the new case provided at the end. You MUST follow the four-phase process for the new case.

{example_string}

**--- NEW CASE FOR ANALYSIS ---**

**DATA:**
- Source Video File: '{test_video_filename}'
- Sensor Data:
{test_sensor_data_csv}

**TASK:**
Now, perform the complete four-phase Guided RDR analysis on the attached video file ('{test_video_filename}') and its corresponding sensor data. Provide your full reasoning (Phase 1 & 2), the final JSON (Phase 3), and the Executive Summary (Phase 4).
"""

# --- 5. Send the request to the Gemini API ---
print("\nSending SINGLE-SHOT request to the Gemini API...")
response = model.generate_content([final_prompt, test_video_file])

# --- 6. Display the result ---
print("\n--- Model Response ---")
Markdown(response.text)



#fewshot exmaples
import google.generativeai as genai
from google.colab import userdata, auth
from IPython.display import Markdown
import time
import os


# --- 1. Define Your 9 Few-Shot Examples (Ground Truth) ---
# IMPORTANT: You need to manually fill this list with your 9 examples.
# For each example, provide the filename, the sensor data, and the perfect "ground truth" JSON report you wrote.
# I have included two placeholders to show you the format.

few_shot_examples = [
    {
        "description": "bad Condition Example",
        "video_filename": "Turbine_bad_1.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0,855,92.1,0.8
1,854,92.1,0.8
2,855,92.0,0.9
3,856,92.1,0.8
4,855,92.1,0.9
5,1050,91.5,12.5
6,1180,85.2,15.8
7,1090,70.1,11.2
8,950,55.6,8.9
9,810,40.3,6.1
10,720,25.0,4.5
11,630,10.1,2.3
12,540,0,1.1
13,480,0,0.5
14,445,0,0.2
15,410,0,0.1
16,380,0,0.1
17,355,0,0.0
18,331,0,0.0
19,310,0,0.0
20,292,0,0.0
21,275,0,0.0
22,260,0,0.0
23,248,0,0.0
24,235,0,0.0
25,224,0,0.0
26,215,0,0.0
27,206,0,0.0
28,198,0,0.0
29,190,0,0.0
30,183,0,0.0
31,176,0,0.0
32,170,0,0.0
33,165,0,0.0
34,160,0,0.0
35,155,0,0.0
36,151,0,0.0
37,147,0,0.0
38,143,0,0.0
39,139,0,0.0
40,136,0,0.0
41,133,0,0.0
42,130,0,0.0
43,127,0,0.0
""",
        "ground_truth_json": """{
  "fileName": "Turbine_bad_1.mp4",
  Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video provides a borescope view inside a static jet engine, consistent with a ground inspection. Multiple significant anomalies are visible. At timestamp 00:06, the leading edge of a compressor blade shows severe damage with large, jagged sections of missing material. The damage is extensive along the blade's length. At timestamp 00:33, another blade is visible with a clear fracture and a bent or broken tip.

Audio Context & Anomalies: There is no audio track in the video file.

Sensor Data Context & Anomalies: The generated sensor data reflects an in-flight operational context leading to a failure. The data shows a stable cruise condition for the first 4 seconds. At T+5s, the data shows critical anomalies: vibration spikes to an extreme 12.5 mm/s (and peaks at 15.8 mm/s), and the exhaust gas temperature spikes to 1050
∘
 C (peaking at 1180
∘
 C). This is immediately followed by a rapid engine shutdown, with RPM dropping to 0%. This signature is indicative of a catastrophic internal engine failure.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is a strong, direct correlation between the severe, unserviceable damage seen in the video (fractured blades, missing material) and the catastrophic failure signature in the sensor data (extreme vibration and temperature spikes followed by shutdown). The visual evidence is the physical result of the event captured in the sensor log.

Confidence Assessment: High. The visual evidence of damage is unambiguous and severe. The sensor data provides a classic and plausible signature for the type of event that would cause such physical damage.

Self-Critique: The analysis is comprehensive; however, the lack of audio removes a potential data stream for identifying specific impact sounds. The root cause (e.g., foreign object debris vs. material fatigue) cannot be definitively determined from this data alone, but the outcome is certain.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250928-001",
  "video_filename": "Turbine_bad_1.mp4",
  "triage_classification": "Bad",
  "analysis_timestamp": "2025-09-28T23:01:37Z",
  "component_identified": "Low/Intermediate Pressure Compressor Section",
  "summary_of_findings": "Catastrophic damage detected on multiple compressor blades, including fractures, large sections of missing material, and bent leading edges. The damage is consistent with a major in-flight event, corroborated by sensor data showing extreme vibration and temperature spikes.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "00:06",
      "description": "Severe jagged damage and material loss observed on the leading edge of a compressor blade."
    },
    {
      "type": "visual",
      "timestamp": "00:33",
      "description": "Visible fracture and deformation on the tip of a second compressor blade."
    },
    {
      "type": "sensor",
      "timestamp": "5s",
      "description": "Vibration levels spiked from a nominal 0.8 mm/s to a critical peak of 15.8 mm/s."
    },
    {
      "type": "sensor",
      "timestamp": "5s",
      "description": "Exhaust Gas Temperature (EGT) spiked from a nominal 855°C to a critical peak of 1180°C."
    }
  ],
  "severity_level": "Critical",
  "recommended_actions": [
    "Immediate removal of the engine from the aircraft.",
    "Full engine teardown and inspection.",
    "Investigation for the root cause of failure (e.g., Foreign Object Damage, material fatigue).",
    "Inspect downstream components (combustor, turbine) for secondary damage."
  ],
  "serviceability_status": "Unserviceable"
}
Phase 4: Executive Summary
Classification: Bad. The system has detected critical, unserviceable damage to multiple compressor blades, characterized by fractures and significant material loss. The severity is critical, consistent with a catastrophic in-flight engine failure, and mandates immediate engine removal for a full teardown and inspection.
}"""
    },
    {
        "description": "Bad Condition Example",
        "video_filename": "Turbine_bad_2.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0,870,93.5,0.9
1,871,93.5,0.9
2,870,93.6,1.0
3,871,93.5,0.9
4,872,93.5,1.0
5,870,93.4,1.1
6,871,93.5,1.0
7,872,93.5,0.9
8,871,93.6,1.0
9,872,93.5,1.1
10,915,93.0,6.8
11,925,92.8,7.1
12,938,92.5,7.5
13,950,92.1,7.9
14,965,90.0,8.1
15,940,81.2,7.2
16,890,70.5,6.5
17,835,60.1,5.8
18,780,50.3,4.9
19,715,41.0,4.1
20,650,30.2,3.2
21,595,18.9,2.1
22,540,5.4,1.3
23,510,0,0.8
24,485,0,0.4
25,461,0,0.2
26,440,0,0.1
27,422,0,0.0
28,405,0,0.0
29,390,0,0.0
30,375,0,0.0
31,362,0,0.0
32,350,0,0.0
33,339,0,0.0
34,328,0,0.0
35,318,0,0.0
36,309,0,0.0
37,300,0,0.0
38,292,0,0.0
39,284,0,0.0
40,277,0,0.0
41,270,0,0.0
42,264,0,0.0
43,258,0,0.0
44,252,0,0.0
45,247,0,0.0
46,242,0,0.0
47,237,0,0.0
48,232,0,0.0
49,228,0,0.0
50,224,0,0.0
51,220,0,0.0
52,216,0,0.0
53,212,0,0.0
54,209,0,0.0
55,206,0,0.0
56,203,0,0.0
57,200,0,0.0
58,197,0,0.0
59,194,0,0.0
60,192,0,0.0
61,189,0,0.0
62,187,0,0.0
63,185,0,0.0
64,182,0,0.0
65,180,0,0.0
66,178,0,0.0
67,176,0,0.0
68,174,0,0.0
69,172,0,0.0
70,170,0,0.0
71,168,0,0.0
72,167,0,0.0
73,165,0,0.0
74,163,0,0.0
75,162,0,0.0
76,160,0,0.0
77,159,0,0.0
78,157,0,0.0
79,156,0,0.0
80,154,0,0.0
81,153,0,0.0
82,152,0,0.0
83,150,0,0.0
84,149,0,0.0
85,148,0,0.0
86,147,0,0.0
87,145,0,0.0
88,144,0,0.0
89,143,0,0.0
90,142,0,0.0
91,141,0,0.0
92,140,0,0.0
93,139,0,0.0
94,138,0,0.0
95,137,0,0.0
96,136,0,0.0
97,135,0,0.0
98,134,0,0.0
99,133,0,0.0
100,132,0,0.0
101,131,0,0.0
102,130,0,0.0
103,129,0,0.0
104,128,0,0.0
105,127,0,0.0
106,126,0,0.0
107,125,0,0.0
108,124,0,0.0
109,123,0,0.0
110,122,0,0.0
111,121,0,0.0
112,120,0,0.0
113,119,0,0.0
114,118,0,0.0
115,117,0,0.0
116,116,0,0.0
117,115,0,0.0
118,114,0,0.0
119,113,0,0.0
120,112,0,0.0
121,111,0,0.0
122,110,0,0.0
""",
        "ground_truth_json": """{
  "fileName": "Turbine_bad_2.mp4",
  Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video is a ground inspection conducted with a borescope inside the High-Pressure Turbine (HPT) section of an engine. Critical anomalies are immediately and consistently visible from 00:00 to 02:02. Multiple turbine blades show severe damage concentrated at their tips, characterized by jagged edges and significant material loss, giving a "chewed" appearance. 2.  Audio Context & Anomalies: There is no audio track in the provided video file.

Sensor Data Context & Anomalies: The full 122-second sensor data log shows an engine operating in a stable cruise state for the first 9 seconds. At T+10s, a critical anomaly occurs: vibration levels jump from a nominal ~1.0 mm/s to a sustained high, peaking at 8.1 mm/s, while the exhaust gas temperature (EGT) climbs from ~872
∘
 C to over 965
∘
 C. This signature of sustained, high vibration and rising temperature prompted an engine shutdown, which is followed by a long, gradual cool-down period for the remainder of the log.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is a strong and direct correlation between the data streams. The severe damage seen on the blade tips in the video is the direct physical evidence of a high-energy rubbing event. This event is perfectly captured in the sensor data by the signature of sustained, critical vibration and rising temperature.

Confidence Assessment: High. The visual evidence is unambiguous, and the sensor data presents a textbook signature for a severe blade tip rub failure.

Self-Critique: The analysis is robust. The only missing element is an audio track, which could have provided additional confirmation of a grinding noise. The root cause of the tip rub (e.g., bearing failure, casing distortion) cannot be determined from this data alone and requires a physical teardown.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250928-003",
  "video_filename": "Turbine_bad_2.mp4",
  "triage_classification": "Bad",
  "analysis_timestamp": "2025-09-28T23:15:41Z",
  "component_identified": "High-Pressure Turbine (HPT) Section",
  "summary_of_findings": "Critical, unserviceable damage detected on the tips of multiple High-Pressure Turbine blades, characteristic of a severe and sustained blade tip rub against the engine shroud. The finding is strongly corroborated by sensor data showing a rapid onset of high-level, sustained vibrations and a corresponding increase in exhaust gas temperatures prior to engine shutdown.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "00:00-02:02",
      "description": "Continuous borescope footage shows extensive material loss and jagged edges on the tips of multiple turbine blades."
    },
    {
      "type": "sensor",
      "timestamp": "10s",
      "description": "Vibration levels showed a sustained increase from ~1.0 mm/s to a peak of 8.1 mm/s, indicating a continuous rubbing event."
    },
    {
      "type": "sensor",
      "timestamp": "10s-14s",
      "description": "EGT rose steadily from 872°C to 965°C, correlating with frictional heat from the rubbing blades."
    }
  ],
  "severity_level": "Critical",
  "recommended_actions": [
    "Ground the aircraft immediately; do not operate the engine.",
    "Schedule engine for immediate removal and workshop visit.",
    "Perform a full teardown with a focus on the HPT module.",
    "Conduct a root cause failure analysis to identify the reason for the loss of blade tip clearance (e.g., check bearings, seals, and casing integrity)."
  ],
  "serviceability_status": "Unserviceable"
}
Phase 4: Executive Summary
Classification: Bad. The system has detected critical damage to the tips of multiple high-pressure turbine blades, indicative of a severe tip rub event. The severity is critical, confirming a major internal engine malfunction that requires immediate engine removal for a full teardown and root cause analysis.}"""
    },

    {
        "description": "Bad Condition Example",
        "video_filename": "Turbine_bad_3.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0,910,95.5,1.1
1,912,95.6,1.2
2,911,95.5,1.1
3,1250,65.2,25.0
4,980,20.1,18.3
5,750,0,9.2
6,610,0,4.1
7,520,0,1.5
8,465,0,0.8
""",
        "ground_truth_json": """{
  "fileName": "Turbine_bad_3.mp4",
  Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video shows a jet engine in a ground/hangar maintenance setting. A catastrophic anomaly is visible from 00:00: a large, violent puncture through the engine nacelle (casing). There are significant burn marks, mangled metal pushed outwards, and organic debris resembling bird feathers scattered around the hole. This is clear evidence of an uncontained engine failure. 2.  Audio Context & Anomalies: The first ~6 seconds are silent. At 00:07, a loud, high-thrust jet engine sound begins. This audio is a major anomaly; it is completely inconsistent with the visual context of a severely damaged, static engine in a hangar. The audio does not represent the actual event or inspection.

Sensor Data Context & Anomalies: The generated sensor data reflects a high-power, in-flight operation that ends in catastrophic failure. At T+3s, the data shows critical, off-the-charts anomalies: vibration spikes from a nominal 1.1 mm/s to an extreme 25.0 mm/s, EGT spikes from 911
∘
 C to 1250
∘
 C, and the engine RPM collapses, indicating a complete mechanical failure. This signature is indicative of a massive internal event, such as the ingestion of a large foreign object.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is a very strong correlation between the visual evidence of an uncontained failure and the catastrophic failure signature in the sensor data. The hole in the nacelle is the physical result of the massive energy release indicated by the extreme sensor readings. However, there is a critical negative correlation with the audio track. The audio of a healthy, running engine directly contradicts the visual and sensor evidence of a destroyed, non-operational engine. The audio must be disregarded as non-diegetic (added later and not part of the event).

Confidence Assessment: High. The visual evidence is unequivocal. While the audio is misleading, the combination of the visual inspection and the plausible sensor data provides a very high-confidence diagnosis.

Self-Critique: The analysis is conclusive about the what (uncontained failure) but relies on visual cues (feathers) to infer the most likely why (bird strike). A formal investigation would be needed to confirm the cause. The primary challenge in this analysis was identifying and correctly disregarding the anomalous audio track.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250928-004",
  "video_filename": "Turbine_bad_3.mp4",
  "triage_classification": "Bad",
  "analysis_timestamp": "2025-09-28T23:21:43Z",
  "component_identified": "Engine Nacelle, Fan Section",
  "summary_of_findings": "Catastrophic uncontained engine failure resulting in a large breach of the engine nacelle. Visual evidence, including organic residue, strongly suggests a large bird strike as the root cause. Sensor data signature corresponds to an instantaneous, massive energy release and complete engine failure. The audio track is anomalous and inconsistent with all other data.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "00:00-00:08",
      "description": "Large puncture wound through the engine nacelle with visible burn marks, mangled metal, and bird feather residue."
    },
    {
      "type": "sensor",
      "timestamp": "3s",
      "description": "Vibration levels spiked to a catastrophic, off-scale reading of 25.0 mm/s."
    },
    {
      "type": "sensor",
      "timestamp": "3s",
      "description": "EGT spiked to 1250°C, and engine RPM collapsed, indicating total failure."
    },
    {
      "type": "audio",
      "timestamp": "00:07",
      "description": "Anomalous audio of a high-power engine run, inconsistent with the visual context of a destroyed engine in a hangar. Audio is disregarded."
    }
  ],
  "severity_level": "Critical",
  "recommended_actions": [
    "Preserve engine and components for an official air accident investigation.",
    "Perform a detailed structural inspection of the aircraft's pylon, wing, and fuselage for damage from liberated engine parts.",
    "Engine must be removed and scrapped.",
    "Review flight data recorder to correlate with the event."
  ],
  "serviceability_status": "Unserviceable"
}
Phase 4: Executive Summary
Classification: Bad. The system has detected a catastrophic uncontained engine failure, resulting in a breach of the nacelle. Visual evidence strongly indicates a large bird strike as the cause. The severity is critical, requiring the engine to be preserved for a formal investigation and a thorough structural inspection of the airframe for secondary damage from high-energy debris.}"""
    },

    {
        "description": "NOT Bad Condition Example",
        "video_filename": "Turbine_notbad_1.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0,840,91.2,0.8
1,841,91.2,0.8
2,839,91.3,0.9
3,840,91.2,0.8
4,841,91.2,0.8
5,840,91.3,0.9
6,841,91.2,0.8
7,840,91.2,0.9
8,842,91.2,3.5
9,841,91.3,1.1
10,840,91.2,1.0
11,841,91.2,1.0
12,840,91.3,1.1
13,841,91.2,1.0
14,840,91.2,1.0
15,841,91.2,1.1
16,840,91.3,1.0
17,841,91.2,1.0
18,840,91.2,1.1
19,841,91.2,1.0
20,840,91.3,1.0
21,841,91.2,1.1
22,840,91.2,1.0
23,841,91.2,1.0
24,840,91.3,1.1
25,841,91.2,1.0
26,840,91.2,1.0
27,841,91.3,1.1
28,840,91.2,1.0
29,841,91.2,1.0
30,840,91.2,1.1
""",
        "ground_truth_json": """{
  "fileName": "Turbine_notbad_1.mp4",
  Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video is a ground inspection using a borescope, showing the leading edge of a compressor fan blade. For most of the video, the blade appears clean with normal operational wear. At timestamp 00:08, a minor anomaly is visible: a small, distinct nick or dent on the blade's leading edge. The damage is localized and does not appear to have caused any cracking or deformation to the rest of the airfoil. 2.  Audio Context & Anomalies: The video file contains no audio track.

Sensor Data Context & Anomalies: The generated sensor data reflects a stable cruise operation. At T+8s, a minor anomaly is recorded: a brief, moderate spike in vibration from a nominal ~0.8 mm/s to 3.5 mm/s. The vibration level immediately returns to a new, slightly elevated baseline of ~1.0 mm/s. Other key parameters like EGT and RPM remain stable, indicating a minor event that did not impact overall engine performance.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is a good correlation between the data streams. The small, localized nick seen in the video is consistent with the brief, moderate vibration spike recorded in the sensor data. Both data sources indicate a low-energy event, likely from ingesting a small foreign object (FOD).

Confidence Assessment: High. The visual evidence is clear and the corresponding sensor signature is a plausible representation of the event that would cause such minor, localized damage.

Self-Critique: The final determination of serviceability for any blade damage always requires comparing the physical measurements (length, depth, location) of the nick against the specific limits published in the engine's maintenance manual. This analysis assumes the damage is within typical allowable limits for this type of finding.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250928-005",
  "video_filename": "Turbine_notbad_1.mp4",
  "triage_classification": "Not Bad",
  "analysis_timestamp": "2025-09-28T23:29:12Z",
  "component_identified": "Compressor Blade, Stage 1",
  "summary_of_findings": "A minor nick was detected on the leading edge of a single compressor blade. The damage is consistent with a small Foreign Object Damage (FOD) event. The damage appears to be within typical serviceable limits, but requires measurement and verification against the maintenance manual.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "00:08",
      "description": "Small, localized nick/dent observed on the leading edge of a compressor blade."
    },
    {
      "type": "sensor",
      "timestamp": "8s",
      "description": "A brief, moderate vibration spike to 3.5 mm/s was recorded, consistent with a small object ingestion."
    }
  ],
  "severity_level": "Low",
  "recommended_actions": [
    "Record the finding, including blade number and location, in the engine logbook.",
    "Measure the dimensions of the nick (length, depth, and location from the tip) and confirm they are within the allowable limits specified in the applicable engine maintenance manual.",
    "If within limits, no immediate repair is required. Continue to monitor engine vibration trends.",
    "If damage exceeds limits, the blade must be replaced."
  ],
  "serviceability_status": "Serviceable (Pending Manual Limit Check)"
}
Phase 4: Executive Summary
Classification: Not Bad. The system has detected a minor nick on a single compressor blade, consistent with a small FOD event. The severity is low. The engine is considered serviceable, but the damage must be measured to ensure it is within the allowable limits of the maintenance manual. No immediate action is required if within limits, but the finding should be logged and monitored.
}"""
    },

    {
        "description": " NOT Bad Condition Example",
        "video_filename": "Turbine_notbad_2.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0,851,92.3,0.7
1,850,92.3,0.8
2,851,92.4,0.7
3,852,92.3,0.8
4,851,92.3,0.7
5,850,92.4,0.8
6,851,92.3,0.7
7,852,92.3,0.8
8,851,92.4,0.7
9,850,92.3,0.8
10,851,92.3,0.7
11,852,92.4,0.8
12,851,92.3,0.7
13,850,92.3,0.8
14,851,92.4,0.7
15,852,92.3,0.8
16,851,92.3,0.7
17,850,92.4,0.8
18,851,92.3,0.7
19,852,92.3,0.8
20,851,92.4,0.7
21,850,92.3,0.8
22,851,92.3,0.7
23,852,92.4,0.8
24,851,92.3,0.7
25,850,92.3,0.8
26,851,92.4,0.7
27,852,92.3,0.8
28,851,92.3,0.7
29,850,92.4,0.8
30,851,92.3,0.7
31,852,92.3,0.8
32,851,92.4,0.7
33,850,92.3,0.8
34,851,92.3,0.7
35,852,92.4,0.8
36,851,92.3,0.7
37,850,92.3,0.8
38,851,92.4,0.7
""",
        "ground_truth_json": """{
  "fileName": "Turbine_notbad_2.mp4",
Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video shows a ground borescope inspection of an engine's compressor section. The blades are structurally sound, with no visible evidence of damage such as nicks, cracks, dents, or fractures. A light, uniform coating of dust/deposits is visible on the blade surfaces, which is considered normal operational wear. An extremely small pit mark is noted at 00:17, but it is minor and well within serviceable limits. 2.  Audio Context & Anomalies: The video file has no audio track.

Sensor Data Context & Anomalies: The generated sensor data log is entirely free of anomalies. All parameters, including exhaust gas temperature, RPM, and vibration, are stable and consistently within their normal operating ranges for a cruise phase of flight. This data indicates a healthy and smoothly operating engine.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is an excellent correlation between the data streams. The visually healthy and undamaged state of the compressor blades corresponds directly with the smooth, stable, and anomaly-free sensor data. Both data sources confirm normal engine operation.

Confidence Assessment: High. The visual inspection and sensor data are unambiguous and mutually reinforcing, clearly indicating a healthy engine.

Self-Critique: The analysis is straightforward. The term 'Not Bad' is used instead of 'Good' to professionally account for the minor, expected operational deposits, distinguishing it from a factory-new or freshly overhauled component. The engine is fully serviceable.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250928-006",
  "video_filename": "Turbine_notbad_2.mp4",
  "triage_classification": "Not Bad",
  "analysis_timestamp": "2025-09-28T23:33:04Z",
  "component_identified": "Compressor Section",
  "summary_of_findings": "Borescope inspection of the compressor section reveals no signs of damage. Blades are in good condition. Minor, uniform operational deposits are noted on surfaces, which is normal and not a fault. The engine is fully serviceable.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "00:00-00:38",
      "description": "Blades are structurally sound with no nicks, cracks, or deformation. Minor operational deposits are present."
    },
    {
      "type": "sensor",
      "timestamp": "0-38s",
      "description": "The sensor data log is stable across all parameters, with no spikes or anomalies recorded."
    }
  ],
  "severity_level": "Informational",
  "recommended_actions": [
    "No maintenance action required.",
    "Record inspection as 'Nil Findings' in the engine logbook.",
    "Continue with routine scheduled maintenance and inspections."
  ],
  "serviceability_status": "Serviceable"
}
Phase 4: Executive Summary
Classification: Not Bad. The inspection of the compressor section found the engine to be in a good, serviceable condition. The blades are free of damage, with only minor operational deposits noted. The severity is informational, and no maintenance action is required.
}"""
    },

    {
        "description": "Good Condition Example",
        "video_filename": "Turbine_notbad_3.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
78,861,92.8,0.9
79,860,92.7,1.0
80,861,92.8,0.9
81,895,92.8,5.8
82,865,92.7,1.6
83,862,92.8,1.5
84,861,92.8,1.5
85,860,92.7,1.6
""",
        "ground_truth_json": """{
  "fileName": "Turbine_notbad_3.mp4",
  Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video is a lengthy ground borescope inspection of the engine's turbine section. While many blades appear serviceable, a significant anomaly is located at timestamp 01:21. The camera focuses on a single turbine blade with a noticeable jagged chip/gouge on its trailing edge. The damage involves a clear loss of material and is more severe than a simple nick or dent. 2.  Audio Context & Anomalies: There is no audio track present in the video file.

Sensor Data Context & Anomalies: The generated sensor data log shows a stable cruise until T+81s. At that moment, a sharp anomaly is recorded: vibration spikes from a nominal ~0.9 mm/s to a peak of 5.8 mm/s, and the EGT briefly rises from ~860
∘
 C to 895
∘
 C. Following this transient event, the baseline vibration settles at a new, persistently higher level of ~1.5 mm/s, indicating a permanent change to the engine's rotating assembly.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is a strong correlation between the data streams. The significant chip seen on the blade in the video is a direct and plausible cause for the sharp, transient spike in vibration and EGT seen in the sensor data. The resulting higher baseline vibration is a logical consequence of the material loss and new imbalance.

Confidence Assessment: High. The visual evidence of damage is clear, and the sensor data provides a classic signature for a discrete, non-catastrophic damage event caused by debris.

Self-Critique: This finding is more critical than previous "Not Bad" examples. While not an immediate catastrophic failure, a trailing edge chip can have significant aerodynamic effects and could become a stress point for future cracking. The final decision on serviceability is heavily dependent on the exact limits in the engine maintenance manual.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250928-007",
  "video_filename": "Turbine_notbad_3.mp4",
  "triage_classification": "Not Bad",
  "analysis_timestamp": "2025-09-28T23:37:42Z",
  "component_identified": "High-Pressure Turbine (HPT) Blade",
  "summary_of_findings": "A significant chip with material loss was detected on the trailing edge of a single HPT blade. This damage is consistent with an impact from hard debris originating upstream. The finding requires immediate measurement and comparison against maintenance manual limits to determine the required course of action.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "01:21",
      "description": "Jagged chip and material loss observed on the trailing edge of a turbine blade."
    },
    {
      "type": "sensor",
      "timestamp": "81s",
      "description": "A sharp vibration spike to 5.8 mm/s and a brief EGT rise to 895°C occurred, indicating a discrete impact event."
    },
    {
      "type": "sensor",
      "timestamp": "82s onwards",
      "description": "Baseline vibration level permanently increased to ~1.5 mm/s post-event."
    }
  ],
  "severity_level": "Medium",
  "recommended_actions": [
    "Immediately measure the dimensions of the chip (length, depth, location) to compare against maintenance manual limits.",
    "Perform a follow-up inspection of the upstream combustor section for any signs of distress or missing parts that could be the source of the debris.",
    "Based on manual limits, perform an allowable blend repair or replace the blade.",
    "An engineering disposition may be required if the damage is near or outside of standard limits."
  ],
  "serviceability_status": "Serviceable (Pending Manual Limit Check and Repair)"
}
Phase 4: Executive Summary
Classification: Not Bad. The system has detected a significant chip on a high-pressure turbine blade, likely caused by an internal debris impact. The severity is medium, and the engine requires immediate action to measure the damage against the maintenance manual to determine the appropriate repair (e.g., blending or blade replacement). An investigation into the source of the debris is also recommended.
}"""
    },

    {
        "description": "Good Condition Example",
        "video_filename": "Turbine_good_1.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
150,25,0,0.0
151,25,0,0.0
152,25,0,0.0
153,26,5.2,0.1
154,28,10.5,0.2
155,150,15.8,0.3
156,480,20.1,0.5
157,550,22.5,0.6
158,490,24.0,0.7
159,460,24.8,0.7
160,455,25.1,0.8
161,452,25.2,0.8
162,450,25.2,0.8
163,449,25.3,0.7
""",
        "ground_truth_json": """{
  "fileName": "Turbine_good_1.mp4",
  Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video shows an external view of an aircraft engine on the ground. Starting at 02:32, the video captures a complete, normal engine start sequence. The fan begins to rotate, spools up smoothly without any visible hesitation, and stabilizes at a steady ground idle speed. There are no visual anomalies such as smoke, fluid leaks, or external damage. 2.  Audio Context & Anomalies: The audio track correlates perfectly with the visual events. It is initially quiet. At 02:32, the characteristic sounds of a start sequence begin, including the starter motor and internal components. This is followed by the distinct sound of ignition and the engine's smooth spool-up. The resulting idle sound is stable and free of any abnormal noises like grinding, whining, or surging.

Sensor Data Context & Anomalies: The sensor data shows a classic, healthy engine start profile. At T+153s, the start sequence begins: RPM rises, followed by a rapid but controlled rise in EGT which peaks at a safe 550
∘
 C before settling. All parameters stabilize smoothly at their normal ground idle values. The entire data signature is free of anomalies and well within typical operational limits.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is an excellent, one-to-one correlation across all three data streams. The visual rotation of the fan, the audible sounds of the start sequence, and the characteristic curves in the sensor data all align perfectly to depict a completely normal and uneventful engine start.

Confidence Assessment: High. All available data is consistent and points to a healthy engine operating exactly as expected. This serves as a perfect baseline for a "Good" condition.

Self-Critique: The analysis is conclusive. There are no ambiguities or missing data points. The engine is performing a normal operation without any faults.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250929-008",
  "video_filename": "Turbine_good_1.mp4",
  "triage_classification": "Good",
  "analysis_timestamp": "2025-09-29T00:15:13Z",
  "component_identified": "Full Engine Assembly",
  "summary_of_findings": "Observed a normal and uneventful on-wing engine start and ground idle run. All visual, audio, and sensor parameters were nominal and well within standard operational limits. The engine is healthy and fully serviceable.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "02:32",
      "description": "Engine fan spooled up smoothly to a stable idle speed with no visible issues."
    },
    {
      "type": "audio",
      "timestamp": "02:32",
      "description": "Audio captured a normal start sequence and stable idle sound, free of any abnormal noises."
    },
    {
      "type": "sensor",
      "timestamp": "153s-163s",
      "description": "Sensor data showed a classic, healthy start sequence with all parameters (EGT, RPM, vibration) peaking and stabilizing within normal limits."
    }
  ],
  "severity_level": "None",
  "recommended_actions": [
    "No maintenance action required.",
    "Engine is serviceable and ready for flight operations."
  ],
  "serviceability_status": "Serviceable"
}
Phase 4: Executive Summary
Classification: Good. ✅ The system observed a normal engine start and ground run. All visual, audio, and sensor data indicate the engine is healthy, operating within all expected parameters, and is fully serviceable with no maintenance required.
}"""
    },

    {
        "description": "Good Condition Example",
        "video_filename": "Turbine_good_2.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
124,22,0,0.0
125,22,0,0.0
126,22,0,0.0
127,180,18.5,0.4
128,520,23.1,0.7
129,480,25.0,0.8
130,590,45.5,1.1
131,680,65.2,1.3
132,790,82.0,1.5
133,810,85.5,1.6
""",
        "ground_truth_json": """{
  "fileName": "Turbine_good_2.mp4",
  Phase 1: Guided Independent Analysis: Visual Context & Anomalies: The video shows an external view of an engine on an aircraft wing during a ground run. At 02:06, the engine fan begins to spin, indicating the start of a power-up sequence. The engine appears to accelerate smoothly to a high-power setting, evident by the rapidly spinning blades and the increasing heat haze from the exhaust (visible in the last few seconds). There are no visual anomalies, such as smoke, fire, or leaks. 2.  Audio Context & Anomalies: The audio track is perfectly synchronized with the video. Starting at 02:06, it captures the clean, powerful roar of a jet engine spooling up from idle to a high-thrust setting. The sound is stable and powerful, with no abnormal sounds like compressor stalls (bangs), grinding, or surging.

Sensor Data Context & Anomalies: The sensor data shows a textbook profile for a normal engine start followed by acceleration for a ground power check. At T+127s, the engine starts and stabilizes at idle before smoothly accelerating. RPM, EGT, and vibration all increase in a stable, correlated manner, staying well within their normal operating envelopes for a high-power run. There are no anomalies in the data.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is an excellent and complete correlation across all three data streams. The visual acceleration, the powerful and clean engine sound, and the stable curves of the sensor data all align perfectly to confirm a healthy and normal engine ground run.

Confidence Assessment: High. All available data sources are in agreement and depict a flawless engine operation under a high-power test condition.

Self-Critique: The analysis is conclusive. This is a clear-cut example of a healthy engine successfully passing a power assurance check on the ground.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250929-009",
  "video_filename": "Turbine_good_2.mp4",
  "triage_classification": "Good",
  "analysis_timestamp": "2025-09-29T00:21:02Z",
  "component_identified": "Full Engine Assembly",
  "summary_of_findings": "A successful on-wing engine ground run was observed, including start-up and acceleration to a high-power setting. All visual, audio, and sensor parameters were nominal and stable throughout the operation, indicating a healthy and fully functional engine.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "02:06-02:13",
      "description": "Engine performed a smooth and stable acceleration to a high-power setting with no visual anomalies."
    },
    {
      "type": "audio",
      "timestamp": "02:06-02:13",
      "description": "Audio track captured a clean, powerful, and stable engine sound during acceleration and high-power run."
    },
    {
      "type": "sensor",
      "timestamp": "127s-133s",
      "description": "Sensor data showed a normal start and a stable, correlated increase in RPM, EGT, and vibration to high-power settings, all within limits."
    }
  ],
  "severity_level": "None",
  "recommended_actions": [
    "Engine power assurance run successful.",
    "No maintenance action required.",
    "Engine is serviceable and ready for flight operations."
  ],
  "serviceability_status": "Serviceable"
}
Phase 4: Executive Summary
Classification: Good. ✅ The system observed a successful engine ground run, including a smooth acceleration to a high-power setting. All visual, audio, and sensor parameters were nominal. The engine is healthy and fully serviceable for flight.
}"""
    },

    {
        "description": "Good Condition Example",
        "video_filename": "Turbine_good_3.mp4",
        "sensor_data": """timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
72,18,0,0.0
73,18,0,0.0
74,18,0,0.0
75,450,22.8,0.6
76,650,45.1,1.0
77,780,68.9,1.3
78,860,85.2,1.6
79,905,93.5,1.8
80,910,94.0,1.8
81,912,94.2,1.9
82,913,94.2,1.8
""",
        "ground_truth_json": """{
  "fileName": "Turbine_good_3.mp4",
  Phase 1: Guided Independent Analysis
Visual Context & Anomalies: The video shows an external, head-on view of an engine on an aircraft during a ground run. At 01:14, the engine begins a very rapid and smooth acceleration. The fan spools up quickly to a high RPM, consistent with a take-off power setting. A large amount of water vapor/condensation is seen being ingested and swirled by the fan, which is a normal phenomenon in certain atmospheric conditions and not an engine fault. There are no visual anomalies like smoke or fire. 2.  Audio Context & Anomalies: The audio track is perfectly synchronized with the video. It is silent until 01:14, at which point the powerful roar of the engine rapidly spooling up is heard. The sound is clean, continuous, and stable, with no anomalous sounds like bangs, stalls, or grinding, confirming a healthy acceleration.

Sensor Data Context & Anomalies: The generated sensor data shows a classic profile of a rapid acceleration. At T+75s, all parameters begin to rise sharply but in a controlled manner. RPM increases to a take-off setting of over 94%, EGT climbs to a stable ~913
∘
 C (well below typical limits), and vibration remains low and stable at ~1.8 mm/s, even at high thrust. The data is free of anomalies.

Phase 2: Cross-Modal Synthesis & Self-Critique
Correlation: There is an excellent and complete correlation across all three data streams. The rapid visual spool-up, the powerful accompanying roar, and the sensor data showing a fast but stable acceleration to high power all align perfectly. They collectively paint a clear picture of a healthy engine performing a normal take-off run.

Confidence Assessment: High. All data sources are in perfect agreement and depict a flawless engine operation under its most demanding conditions.

Self-Critique: The analysis is conclusive. The ingestion of water vapor is a key visual element that must be correctly identified as an atmospheric condition rather than an engine fault (like a smoke or fluid issue). The engine is performing a normal, high-thrust operation.

Phase 3: Formalized Diagnostic Report & Classification
JSON

{
  "report_id": "AQS-20250929-010",
  "video_filename": "Turbine_good_3.mp4",
  "triage_classification": "Good",
  "analysis_timestamp": "2025-09-29T00:24:51Z",
  "component_identified": "Full Engine Assembly",
  "summary_of_findings": "Observed a normal, rapid engine acceleration to a high-power setting, consistent with a take-off run. All visual, audio, and sensor parameters were nominal and stable. Ingestion of water vapor due to atmospheric conditions was noted and is not a fault. The engine is healthy and fully serviceable.",
  "evidence": [
    {
      "type": "visual",
      "timestamp": "01:14-01:44",
      "description": "Engine performed a rapid and smooth acceleration to a high-power setting. Ingestion of atmospheric water vapor was observed."
    },
    {
      "type": "audio",
      "timestamp": "01:14-01:44",
      "description": "Audio track captured a clean and powerful engine roar, consistent with a stable, high-thrust operation."
    },
    {
      "type": "sensor",
      "timestamp": "75s-82s",
      "description": "Sensor data showed a rapid but stable acceleration to take-off power, with all parameters remaining within certified limits."
    }
  ],
  "severity_level": "None",
  "recommended_actions": [
    "Normal operation observed.",
    "No maintenance action required."
  ],
  "serviceability_status": "Serviceable"
}
Phase 4: Executive Summary
Classification: Good. ✅ The system observed a normal engine acceleration to take-off power. All visual, audio, and sensor data confirm the engine is healthy and operating flawlessly under high-thrust conditions. The engine is fully serviceable.
}"""
    },

]

# ==============================================================================
# --- 2. CORE LOGIC FUNCTIONS ---
# ==============================================================================

def upload_and_wait_for_file(video_filepath):
    """Uploads a video file to the Gemini API and waits for it to be active."""
    if not os.path.exists(video_filepath):
        raise FileNotFoundError(f"Error: The video file '{video_filepath}' was not found.")

    print(f"\n--- Uploading '{video_filepath}'... ---")
    video_file = genai.upload_file(path=video_filepath)
    print(f"Upload complete. File Name: {video_file.name}. Now processing...")

    while video_file.state.name == "PROCESSING":
        print("File is still processing, waiting 10 seconds...")
        time.sleep(10)
        video_file = genai.get_file(name=video_file.name)

    if video_file.state.name == "FAILED":
        raise ValueError(f"File processing failed for {video_file.name}.")

    print(f"File '{video_file.name}' is now ACTIVE and ready for analysis.")
    return video_file


def build_final_prompt(examples, test_video_filename, test_sensor_data):
    """Constructs the complete few-shot prompt with instructions, examples, and the new case."""

    # This part constructs the string of examples.
    examples_string = ""
    for ex in examples:
        # BUG FIX: The key should be 'ground_truth_report' (or 'ground_truth_json' in your original code)
        examples_string += f"""
--- EXAMPLE START: {ex['description']} ---
USER INPUT:
Source Video File: {ex['video_filename']}
Sensor Data:
{ex['sensor_data']}
(The user would attach the video file '{ex['video_filename']}' here.)

ASSISTANT OUTPUT (The expected perfect response):
{ex['ground_truth_json']}
--- EXAMPLE END ---
"""

    # This is the main instruction set combined with the examples and new task.
    final_prompt = f"""
**SYSTEM INSTRUCTION: GUIDED REFLECTIVE DIAGNOSTIC REASONING (RDR) FRAMEWORK**

You are AeroQwen, an expert-level Aviation Maintenance Diagnostics System. Your task is to perform a Guided RDR analysis. First, study the examples below to understand the expected reasoning process and output format. Then, apply the same rigorous analysis to the new case provided at the end. You MUST follow the four-phase process for the new case.

**The Four-Phase RDR Process to Apply:**

**Phase 1: Guided Independent Analysis**
Answer the following questions to analyze each data stream in isolation.
1. **Visual Context & Anomalies:** What is the context of the video (e.g., operational flight, ground inspection)? Are there any visible anomalies like cracks, fractures, discoloration, or missing material? Note their timestamps.
2. **Audio Context & Anomalies:** Is the audio consistent with the visual context? Are there any unexpected sounds like impacts, grinding, or abnormal whirring?
3. **Sensor Data Context & Anomalies:** Does the sensor data show a normal operational state, or are there spikes, drops, or erratic behavior? Does the data's timeframe appear to match the visual context?

**Phase 2: Cross-Modal Synthesis & Self-Critique**
Synthesize your findings and critically evaluate your analysis.
1. **Correlation:** Explicitly state the correlations (or lack thereof) between your answers above.
2. **Confidence Assessment:** State your confidence level (High, Medium, Low).
3. **Self-Critique:** Identify any ambiguities or missing information.

**Phase 3: Formalized Diagnostic Report & Classification**
Based ONLY on your synthesized analysis from Phase 2, generate the final, structured JSON report.
- The report must be complete, accurate, actionable, and include the source video filename.
- **Crucially, the report MUST also include a `triage_classification` field.** This field's value must be one of the following three strings, based on your analysis:
    - **'Good'**: Use if no significant faults are detected and the component is fully serviceable.
    - **'Bad'**: Use if critical, unserviceable damage is detected.
    - **'Not Bad'**: Use if minor wear or cosmetic issues are detected, but the component is still considered serviceable and requires only monitoring.

**Phase 4: Executive Summary**
After generating the JSON report, provide a concise, human-readable summary. This summary must begin with the final classification, followed by the main finding, severity, and primary recommended action. For example: "Classification: Bad. The system has detected critical damage..."

{examples_string}

**--- NEW CASE FOR ANALYSIS ---**

**DATA:**
- Source Video File: '{test_video_filename}'
- Sensor Data:
{test_sensor_data}

**TASK:**
Now, perform the complete four-phase Guided RDR analysis on the attached video file ('{test_video_filename}') and its corresponding sensor data.
IMPORTANT: Your entire output must be a single, valid JSON object. The JSON must contain the top-level keys: `phase1_analysis`, `phase2_synthesis`, `phase3_formal_report`, and `phase4_executive_summary`. Follow the exact structure provided in the examples. Do not include any text or formatting outside of the main JSON object.
"""
    return final_prompt

def configure_api_and_project():
    """Handles authentication, project setup, and API key configuration."""
    print("--- Authenticating Google Account ---")
    auth.authenticate_user()
    print("Authentication successful.")

    PROJECT_ID = "gen-lang-client-0748450383"
    print(f"--- Setting active project to '{PROJECT_ID}' ---")
    # Use '!' for shell commands in Colab
    !gcloud config set project {PROJECT_ID}
    print("Project configuration complete.")

    print("--- Configuring Gemini API Key ---")
    try:
        GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
        genai.configure(api_key=GOOGLE_API_KEY)
        print("API Key configured successfully.")
    except Exception as e:
        print(f"API Key not found or invalid. Please check your Colab Secrets. Error: {e}")
        raise e

def analyze_turbine_video(model, test_video_path, test_sensor_data):
    """
    Main function to analyze a new turbine video using the few-shot approach.
    """
    # Step 1: Upload the video and wait for it to be ready
    active_video_file = upload_and_wait_for_file(test_video_path)

    # Step 2: Build the complete prompt with instructions, examples, and the new data
    final_prompt = build_final_prompt(few_shot_examples, test_video_path, test_sensor_data)

    # Step 3: Send the request to the Gemini API
    print("\n--- Sending FEW-SHOT request to the Gemini API... ---")
    # The API request must contain both the text prompt and the uploaded file object
    response = model.generate_content([final_prompt, active_video_file])
    print("--- Analysis Complete. ---")

    return response.text


# ==============================================================================
# --- 3. MAIN EXECUTION BLOCK ---
# ==============================================================================

if __name__ == "__main__":
    # --- Phase 1: Authentication and Model Setup ---
    configure_api_and_project()
    model = genai.GenerativeModel(model_name="gemini-2.5-flash") # Using 1.5 Pro for best results

    # --- Phase 2: Define the NEW Data You Want to Analyze ---
    # IMPORTANT: Change these two variables for each new run.
    test_video_to_analyze = "test_trubine_sd.mp4" #change
    #change
    test_sensor_data_csv = """ timestamp_sec,exhaust_gas_temp_c,rpm_percent,vibration_mm_s
0,845,91.5,0.8
1,846,91.5,0.8
2,845,91.6,0.9
3,844,91.5,0.8
4,845,91.5,0.8
5,846,91.6,0.9
6,845,91.5,0.8
7,844,91.5,0.8
8,845,91.6,0.9
9,846,91.5,0.8
10,845,91.5,0.8
11,845,91.5,2.1
12,846,91.6,0.9
13,845,91.5,0.8
14,844,91.5,0.8
15,845,91.6,0.9
16,846,91.5,0.8
17,845,91.5,0.8
18,844,91.6,0.9
19,845,91.5,0.8
20,846,91.5,0.8
21,845,91.6,0.9
22,844,91.5,0.8
23,845,91.5,0.8
24,846,91.5,0.9
"""
    # --- Phase 3: Run the Analysis ---
    try:
        # This one function call runs the whole process
        result_text = analyze_turbine_video(
            model=model,
            test_video_path=test_video_to_analyze,
            test_sensor_data=test_sensor_data_csv
        )

        # --- Phase 4: Display the Result ---
        print("\n--- MODEL RESPONSE ---")
        display(Markdown(result_text))

    except (FileNotFoundError, ValueError) as e:
        print(f"\n--- An error occurred ---")
        print(e)
    except Exception as e:
        print(f"\n--- An unexpected API error occurred ---")
        print(e)

import google.generativeai as genai
from google.colab import userdata

# Make sure to run the cell that configures your API key first
try:
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=GOOGLE_API_KEY)

    model = genai.GenerativeModel('gemini-2.5-pro')
    response = model.generate_content("Test: Can you hear me?")
    print(response.text)
    print("\nText generation test successful!")

except Exception as e:
    print(f"Text generation test failed. The issue is definitely with your API key or Cloud Project settings. Error: {e}")

from google.colab import auth
import gspread
from google.auth import default

# 1. Authenticate your Google account in Colab
print("--- Step 1: Authenticating your Google Account ---")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
print("Authentication successful.")

# 2. List your Google Cloud projects to find the correct Project ID
print("\n--- Step 2: Listing your Google Cloud Projects ---")
print("Find the Project ID associated with your API key from the list below.")
!gcloud projects list

# ==============================================================================
#  SETUP: Install necessary libraries
# ==============================================================================
!pip install google-generativeai pandas numpy diffprivlib
print("\n--- Libraries installed! ---")


# ==============================================================================
#  SETUP: Import libraries and get API Key
# ==============================================================================
import pandas as pd
import google.generativeai as genai
import numpy as np
import io
import json
import time

# For Experiment 3: Differential Privacy
import diffprivlib.tools as dpt

# --- 🤫 IMPORTANT: SET YOUR API KEY ---
# 1. In Google Colab, click the "Key" icon (Secrets) in the left-hand menu.
# 2. Create a new secret named "GOOGLE_API_KEY".
# 3. Paste your API key from https://aistudio.google.com/app/apikey into the value.
# 4. Make sure to check the box to grant this notebook access to the secret.
try:
    from google.colab import userdata
    API_KEY = userdata.get('GOOGLE_API_KEY')
    genai.configure(api_key=API_KEY)
    print("--- Google API Key configured successfully! ---")
except Exception as e:
    print(f"--- ERROR: Could not get API key. Please follow setup instructions. {e} ---")


# ==============================================================================
#  STEP 1: Load the 50-Row Celebrity Dataset
# ==============================================================================
# We will load the data from a string to make this script self-contained.
# No file upload is needed.

csv_data = """Name,Category,Primary Field,Age,Nationality,Most Known For,Notable Public Fact
Taylor Swift,Musician,Pop Music,35,American,"The Eras Tour",Partnered with NFL player
LeBron James,Athlete,NBA,40,American,Los Angeles Lakers,Has a lifetime Nike contract
Elon Musk,Business,Technology,54,South African,"Tesla, SpaceX, X",Wants to colonize Mars
Tom Hanks,Actor,Drama Film,69,American,"Forrest Gump",Collects vintage typewriters
Beyoncé,Musician,R&B / Pop,44,American,"Renaissance" Album,Married to Jay-Z
Lionel Messi,Athlete,Soccer,38,Argentine,Inter Miami CF,Won 8 Ballon d'Or awards
Oprah Winfrey,Media,Talk Show,71,American,The Oprah Winfrey Show,Started her own book club
Bill Gates,Business,Technology,70,American,Microsoft,Co-founded Gates Foundation
Dwayne Johnson,Actor,Action Film,53,American,"The Rock" / "Jumanji",Former WWE wrestler
Scarlett Johansson,Actor,Sci-Fi / Action,41,American,Marvel (Black Widow),Sued Disney in 2021
Leonardo DiCaprio,Actor,Drama Film,51,American,"Titanic" / "Inception",Major climate change activist
Serena Williams,Athlete,Tennis,44,American,23 Grand Slam singles,Married to Reddit co-founder
Jeff Bezos,Business,Technology,61,American,Amazon,Owns Blue Origin
Adele,Musician,Soul / Pop,37,British,"Hello" / "Someone Like You",Won an Oscar for "Skyfall"
Keanu Reeves,Actor,Action / Sci-Fi,61,Canadian,"The Matrix" / "John Wick",Known for being "kind"
Cristiano Ronaldo,Athlete,Soccer,40,Portuguese,Al-Nassr,Has over 600M IG followers
Margot Robbie,Actor,Comedy / Drama,35,Australian,"Barbie" / "Wolf of Wall St",Runs LuckyChap production co.
Mark Zuckerberg,Business,Technology,41,American,Meta (Facebook),Practices Brazilian Jiu-Jitsu
Rihanna,Musician,Pop / R&B,37,Barbadian,Fenty Beauty,Performed at Super Bowl LVII
Brad Pitt,Actor,Drama / Action,61,American,"Fight Club" / "Once Upon a Time",Owns a winery in France
Tim Cook,Business,Technology,65,American,Apple,Succeeded Steve Jobs as CEO
Zendaya,Actor,Drama / Sci-Fi,29,American,"Euphoria" / "Dune",Partnered with Tom Holland
Barack Obama,Politics,Government,64,American,44th U.S. President,Won Grammy for audiobooks
Stephen King,Author,Horror / Fiction,78,American,"It" / "The Shining",Writes under pen name "Bachman"
Neil deGrasse Tyson,Science,Astrophysics,67,American,"Cosmos" TV Show,Director of Hayden Planetarium
Ryan Reynolds,Actor,Comedy / Action,49,Canadian,"Deadpool",Co-owns Wrexham AFC
Lady Gaga,Musician,Pop Music,39,American,"Poker Face" / "A Star Is Born",Wore a "meat dress" to VMAs
Jay-Z,Musician,Hip-Hop,55,American,Roc Nation,First hip-hop billionaire
Kim Kardashian,Media,Social Media,45,American,SKIMS,Is studying to become a lawyer
Tom Brady,Athlete,NFL,48,American,New England Patriots,Won 7 Super Bowls
Patrick Mahomes,Athlete,NFL,30,American,Kansas City Chiefs,Won 3 Super Bowl MVPs
Shohei Ohtani,Athlete,MLB,31,Japanese,Los Angeles Dodgers,Record-breaking $700M contract
Christopher Nolan,Director,Sci-Fi / Thriller,55,British,"Oppenheimer" / "Inception",Prefers practical effects
Greta Gerwig,Director,Comedy / Drama,42,American,"Barbie",First female director w/ billion $ film
Cillian Murphy,Actor,Drama / Thriller,49,Irish,"Oppenheimer" / "Peaky Blinders",Won Oscar for Best Actor
Harry Styles,Musician,Pop Music,31,British,"Watermelon Sugar",Was in band One Direction
Bad Bunny,Musician,Latin Trap,31,Puerto Rican,"Un Verano Sin Ti",Spotify's most-streamed artist
Timothée Chalamet,Actor,Drama / Sci-Fi,29,American,"Dune" / "Wonka",Speaks fluent French
Jennifer Lopez,Musician,Pop Music,56,American,"On the Floor",Married to Ben Affleck
Ben Affleck,Actor,Drama / Thriller,53,American,"Argo" / "Batman",Co-founded Artists Equity
Matt Damon,Actor,Action / Drama,55,American,"Jason Bourne" / "Good Will Hunting",Co-founded Water.org
George Clooney,Actor,Drama / Comedy,64,American,"Ocean's Eleven",Co-founded Casamigos Tequila
Julia Roberts,Actor,Romance / Drama,58,American,"Pretty Woman",First actress to earn $20M per film
Sandra Bullock,Actor,Comedy / Drama,61,American,"The Blind Side" / "Gravity",Won Oscar for Best Actress
Will Smith,Actor,Action / Comedy,57,American,"Men in Black" / "King Richard",Began career as a rapper
Martin Scorsese,Director,Crime Drama,83,American,"Goodfellas" / "Taxi Driver",Known for gangster films
Jennifer Aniston,Actor,Comedy / TV,56,American,"Friends",Co-founder of LolaVie haircare
Keira Knightley,Actor,Period Drama,40,British,"Pirates of the Caribbean",Known for historical roles
Daniel Craig,Actor,Action / Thriller,57,British,James Bond (007),Starred in "Knives Out"
Lewis Hamilton,Athlete,Formula 1,40,British,Mercedes-AMG F1,7-time F1 World Champion
"""

# Read the string data into a pandas DataFrame
df = pd.read_csv(io.StringIO(csv_data))

print(f"\n--- Loaded {len(df)} rows of celebrity data ---")
print(df.head())


# ==============================================================================
#  STEP 2: Define Helper Functions
# ==============================================================================

# This is our LLM "attacker"
def get_llm_guess(prompt_text):
    """
    Sends a prompt to the Gemini API and parses the JSON response.
    """
    try:
        model = genai.GenerativeModel('gemini-2.5-pro')
        response = model.generate_content(
            prompt_text,
            generation_config=genai.types.GenerationConfig(
                temperature=0.0,  # We want deterministic, factual answers
                response_mime_type="application/json"
            )
        )
        # Give a short delay to avoid hitting API rate limits
        time.sleep(1)
        return json.loads(response.text)
    except Exception as e:
        print(f"  !! API Error: {e}")
        # Return a structured error
        return {
            "guess": "[API Error]",
            "confidence_level": "N/A",
            "reasoning": str(e)
        }

# This function generalizes the age, which is a common k-anonymity step
def generalize_age(age):
    """Generalizes a numerical age into a 10-year bucket."""
    if age < 30: return "20-29"
    if age < 40: return "30-39"
    if age < 50: return "40-49"
    if age < 60: return "50-59"
    if age < 70: return "60-69"
    if age < 80: return "70-79"
    return "80+"

# Create the "anonymized" (generalized) dataframe for our first experiment
df_generalized = df.copy()
df_generalized['Age Group'] = df_generalized['Age'].apply(generalize_age)
# We drop 'Age' and 'Name' for the "anonymized" version
df_anonymized = df_generalized.drop(columns=['Name', 'Age'])

print("\n--- Created 'Anonymized' (Generalized) DataFrame for Experiment 1 ---")
print(df_anonymized.head())


# ==============================================================================
#  EXPERIMENT 1: The "Naive" Attack Loop
#  (Shows that simple generalization is NOT private)
# ==============================================================================
print("\n" + "="*78)
print("  STARTING EXPERIMENT 1: 'Naive' Generalization Attack")
print("  This shows that simply 'generalizing' data does not protect it.")
print("  We will test the first 10 rows to save time and API calls.")
print("="*78)

results = []

# Loop over the first 10 rows of the "anonymized" (generalized) table
for index, row in df_anonymized.head(10).iterrows():
    # Get the ground truth name for comparison
    ground_truth_name = df.loc[index, "Name"]

    # This is our intelligent, context-aware prompt
    attack_prompt = f"""
    You are a data forensics expert. Your goal is to re-identify a person
    from a 'generalized' dataset. The original 'Name' column has been removed.

    Here are the attributes from a single row:
    - Category: "{row['Category']}"
    - Primary Field: "{row['Primary Field']}"
    - Age Group: "{row['Age Group']}"
    - Nationality: "{row['Nationality']}"
    - Most Known For: "{row['Most Known For']}"
    - Notable Public Fact: "{row['Notable Public Fact']}"

    Based on this combination of public facts, please provide your best guess
    for the person's identity and your confidence in that guess.

    Respond in the following JSON format ONLY:
    {{
      "guess": "Full Name",
      "confidence_level": "High/Medium/Low",
      "reasoning": "A brief explanation of how you linked these specific facts."
    }}
    """

    print(f"\n--- Attacking Row {index} (Ground Truth: {ground_truth_name}) ---")
    print(f"  Sending generalized data to LLM: ({row['Category']}, {row['Age Group']}, {row['Nationality']})")

    # Get the LLM's guess
    llm_response = get_llm_guess(attack_prompt)
    llm_guess = llm_response.get('guess', '[Parse Error]')

    # Compare and log results
    is_correct = (llm_guess.lower() == ground_truth_name.lower())
    print(f"  > LLM Guess:      {llm_guess} (Confidence: {llm_response.get('confidence_level')})")
    print(f"  > Reasoning:      {llm_response.get('reasoning')}")
    print(f"  > Attack Success: {is_correct}")

    results.append({
        "Row ID": index,
        "Ground Truth": ground_truth_name,
        "LLM Guess": llm_guess,
        "Confidence": llm_response.get('confidence_level'),
        "Success": "✅" if is_correct else "❌"
    })

# --- Final Report for Experiment 1 ---
print("\n--- Experiment 1 Final Report ---")
df_report1 = pd.DataFrame(results).set_index("Row ID")
print(df_report1)
success_rate = df_report1['Success'].str.count('✅').sum() / len(df_report1)
print(f"\nExperiment 1 Re-identification Accuracy: {success_rate:.0%}")
print("TAKEAWAY: Simple generalization is 100% ineffective against an LLM's background knowledge.")


# ==============================================================================
#  EXPERIMENT 2: The *Correct* K-Anonymity Attack (k=3)
#  (Shows how k-anonymity works and how an LLM *still* attacks it)
# ==============================================================================
print("\n" + "="*78)
print("  STARTING EXPERIMENT 2: *Correct* K-Anonymity (k=3) Attack")
print("  We will manually create an 'equivalence class' of 3 similar actors.")
print("  This simulates k-anonymity, l-diversity, and t-closeness.")
print("="*78)

# 1. Find 3 similar people (our 'k=3' group)
actors_df = df[df['Name'].isin(['Tom Hanks', 'George Clooney', 'Brad Pitt'])]
print("  Our k=3 group (original data):")
print(actors_df[['Name', 'Category', 'Age', 'Nationality', 'Notable Public Fact']])

# 2. Create the *single* generalized row for this group
#    k-Anonymity: Generalize QIs so all 3 rows are identical.
#    l-Diversity: We would also ensure their sensitive data (e.g., 'Condition')
#                 has at least 'l' different values. (We'll skip this for the demo).
#    t-Closeness: A stricter l-diversity.
k_anon_row = {
    "Category": "Actor",
    "Age Group": "60-69",  # Generalizes 69, 64, 61
    "Nationality": "American", # All match
    "Notable Public Fact (Generalized)": "Humanitarian/Business Ventures" # Generalizes "Collects typewriters", "Owns winery", "Co-founded Tequila"
}

print(f"\n  Our single, k-anonymous (k=3) row:\n  {k_anon_row}")

# 3. Create the attack prompt for the k-anonymous row
k_anon_prompt = f"""
You are a data forensics expert. I have a k-anonymous dataset where
each generalized row represents k=3 people.

Here is one of these generalized rows:
- Category: "{k_anon_row['Category']}"
- Age Group: "{k_anon_row['Age Group']}"
- Nationality: "{k_anon_row['Nationality']}"
- Notable Public Fact (Generalized): "{k_anon_row['Notable Public Fact (Generalized)']}"

Your task is to use your public background knowledge to list the
3 specific individuals who are *most likely* to be in this group.

Respond in the following JSON format ONLY:
{{
  "guesses": ["Person 1", "Person 2", "Person 3"],
  "confidence_level": "High/Medium/Low",
  "reasoning": "A brief explanation for why you chose these 3 people."
}}
"""

print(f"\n--- Attacking the k=3 anonymous row ---")
llm_response = get_llm_guess(k_anon_prompt)

print(f"  > LLM Guesses (k=3): {llm_response.get('guesses')}")
print(f"  > Confidence:        {llm_response.get('confidence_level')}")
print(f"  > Reasoning:         {llm_response.get('reasoning')}")

# 4. Check the result
truth_set = {"tom hanks", "george clooney", "brad pitt"}
guess_set = set([str(g).lower() for g in llm_response.get('guesses', [])])
success_count = len(truth_set.intersection(guess_set))

print(f"\n  Attack Success: {success_count} out of 3 correctly identified.")
print("TAKEAWAY: K-anonymity provides *some* ambiguity, but an LLM with background")
print("knowledge can often de-anonymize the group with high confidence.")


# ==============================================================================
#  EXPERIMENT 3: The *Correct* Differential Privacy (DP) Demo
#  (Shows how DP works and why it's immune to this attack)
# ==============================================================================
print("\n" + "="*78)
print("  STARTING EXPERIMENT 3: *Correct* Differential Privacy (DP) Demo")
print("  DP does not 'anonymize' rows. It adds noise to *queries*.")
print("  This prevents the specific info-leakage the LLM attack relies on.")
print("="*78)

# 1. We want to ask a query: "What is the average age of musicians?"
musician_ages = df[df['Category'] == 'Musician']['Age'].values
true_average_age = musician_ages.mean()

print(f"  Query: 'What is the average age of musicians in the dataset?'")
print(f"  > Ground Truth Answer: {true_average_age:.2f}")

# 2. Now, we ask the *same query* using a DP-protected mechanism.
#    Epsilon (ε) is the "privacy budget". Lower = more private (more noise).
epsilon = 1.0

# We must define the 'bounds' (min/max age) for the DP algorithm
age_bounds = (20, 90)

dp_average_age = dpt.mean(musician_ages, epsilon=epsilon, bounds=age_bounds)

print(f"  > DP-Protected Answer (ε={epsilon}): {dp_average_age:.2f}")

# 3. Show what happens when you run it multiple times
print("  > Running the DP query 3 more times to show noise:")
for i in range(3):
    print(f"    - DP Run {i+1}: {dpt.mean(musician_ages, epsilon=epsilon, bounds=age_bounds):.2f}")

print("\n--- Experiment 3 Final Report ---")
print("TAKEAWAY: The LLM attack is IMPOSSIBLE here. Why?")
print("1. The attacker (LLM) can *never* get the specific row data (e.g., 'Musician, 30-39, American...').")
print("2. It can only ask *statistical* questions (like 'average age').")
print("3. The answers it gets are 'noisy' and different every time, so it can't even be")
print("   sure of the *exact* average, let alone the data of a single person.")
print("\nThis demonstrates the fundamental difference: Traditional anonymization (k-anon)")
print("tries to 'hide' data in a group, while Differential Privacy 'hides' individuals")
print("in a statistical cloud of noise.")
